// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch_jobs.sql

package db

import (
	"context"
	"time"
)

const countBatchJobItemsByStatus = `-- name: CountBatchJobItemsByStatus :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN status = 'Pending' THEN 1 ELSE 0 END) as pending,
    SUM(CASE WHEN status = 'Processing' THEN 1 ELSE 0 END) as processing,
    SUM(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN status = 'Failed' THEN 1 ELSE 0 END) as failed
FROM batch_job_items
WHERE batch_job_id = ?
`

type CountBatchJobItemsByStatusRow struct {
	Total      int64    `db:"total" json:"total"`
	Pending    *float64 `db:"pending" json:"pending"`
	Processing *float64 `db:"processing" json:"processing"`
	Completed  *float64 `db:"completed" json:"completed"`
	Failed     *float64 `db:"failed" json:"failed"`
}

// CountBatchJobItemsByStatus
//
//	SELECT
//	    COUNT(*) as total,
//	    SUM(CASE WHEN status = 'Pending' THEN 1 ELSE 0 END) as pending,
//	    SUM(CASE WHEN status = 'Processing' THEN 1 ELSE 0 END) as processing,
//	    SUM(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END) as completed,
//	    SUM(CASE WHEN status = 'Failed' THEN 1 ELSE 0 END) as failed
//	FROM batch_job_items
//	WHERE batch_job_id = ?
func (q *Queries) CountBatchJobItemsByStatus(ctx context.Context, batchJobID string) (CountBatchJobItemsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countBatchJobItemsByStatus, batchJobID)
	var i CountBatchJobItemsByStatusRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Processing,
		&i.Completed,
		&i.Failed,
	)
	return i, err
}

const countBatchJobsByStatus = `-- name: CountBatchJobsByStatus :one
SELECT COUNT(*) FROM batch_jobs
WHERE status = ?
`

// CountBatchJobsByStatus
//
//	SELECT COUNT(*) FROM batch_jobs
//	WHERE status = ?
func (q *Queries) CountBatchJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBatchJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatchJob = `-- name: CreateBatchJob :exec


INSERT INTO batch_jobs (
    id,
    batch_name,
    status,
    queued_at,
    total_files,
    processed_files,
    successful_files,
    failed_files,
    continue_on_error,
    dry_run,
    max_concurrency,
    retry_count,
    max_retries,
    metadata,
    created_date,
    last_update_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateBatchJobParams struct {
	ID              string    `db:"id" json:"id"`
	BatchName       string    `db:"batch_name" json:"batchName"`
	Status          string    `db:"status" json:"status"`
	QueuedAt        time.Time `db:"queued_at" json:"queuedAt"`
	TotalFiles      int64     `db:"total_files" json:"totalFiles"`
	ProcessedFiles  *int64    `db:"processed_files" json:"processedFiles"`
	SuccessfulFiles *int64    `db:"successful_files" json:"successfulFiles"`
	FailedFiles     *int64    `db:"failed_files" json:"failedFiles"`
	ContinueOnError *bool     `db:"continue_on_error" json:"continueOnError"`
	DryRun          *bool     `db:"dry_run" json:"dryRun"`
	MaxConcurrency  *int64    `db:"max_concurrency" json:"maxConcurrency"`
	RetryCount      *int64    `db:"retry_count" json:"retryCount"`
	MaxRetries      *int64    `db:"max_retries" json:"maxRetries"`
	Metadata        *string   `db:"metadata" json:"metadata"`
	CreatedDate     time.Time `db:"created_date" json:"createdDate"`
	LastUpdateDate  time.Time `db:"last_update_date" json:"lastUpdateDate"`
}

// Batch Jobs SQL Queries
// SQLC will generate type-safe Go code from these queries
// ============================================================================
// BATCH JOB QUERIES
// ============================================================================
//
//	INSERT INTO batch_jobs (
//	    id,
//	    batch_name,
//	    status,
//	    queued_at,
//	    total_files,
//	    processed_files,
//	    successful_files,
//	    failed_files,
//	    continue_on_error,
//	    dry_run,
//	    max_concurrency,
//	    retry_count,
//	    max_retries,
//	    metadata,
//	    created_date,
//	    last_update_date
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
//	)
func (q *Queries) CreateBatchJob(ctx context.Context, arg CreateBatchJobParams) error {
	_, err := q.db.ExecContext(ctx, createBatchJob,
		arg.ID,
		arg.BatchName,
		arg.Status,
		arg.QueuedAt,
		arg.TotalFiles,
		arg.ProcessedFiles,
		arg.SuccessfulFiles,
		arg.FailedFiles,
		arg.ContinueOnError,
		arg.DryRun,
		arg.MaxConcurrency,
		arg.RetryCount,
		arg.MaxRetries,
		arg.Metadata,
		arg.CreatedDate,
		arg.LastUpdateDate,
	)
	return err
}

const createBatchJobItem = `-- name: CreateBatchJobItem :exec

INSERT INTO batch_job_items (
    batch_job_id,
    file_hash,
    confirmed_category,
    custom_target_path,
    status,
    metadata,
    created_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateBatchJobItemParams struct {
	BatchJobID        string    `db:"batch_job_id" json:"batchJobId"`
	FileHash          string    `db:"file_hash" json:"fileHash"`
	ConfirmedCategory string    `db:"confirmed_category" json:"confirmedCategory"`
	CustomTargetPath  *string   `db:"custom_target_path" json:"customTargetPath"`
	Status            string    `db:"status" json:"status"`
	Metadata          *string   `db:"metadata" json:"metadata"`
	CreatedDate       time.Time `db:"created_date" json:"createdDate"`
}

// ============================================================================
// BATCH JOB ITEMS QUERIES
// ============================================================================
//
//	INSERT INTO batch_job_items (
//	    batch_job_id,
//	    file_hash,
//	    confirmed_category,
//	    custom_target_path,
//	    status,
//	    metadata,
//	    created_date
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?
//	)
func (q *Queries) CreateBatchJobItem(ctx context.Context, arg CreateBatchJobItemParams) error {
	_, err := q.db.ExecContext(ctx, createBatchJobItem,
		arg.BatchJobID,
		arg.FileHash,
		arg.ConfirmedCategory,
		arg.CustomTargetPath,
		arg.Status,
		arg.Metadata,
		arg.CreatedDate,
	)
	return err
}

const deleteOldBatchJobs = `-- name: DeleteOldBatchJobs :exec
DELETE FROM batch_jobs
WHERE status IN ('Completed', 'Failed', 'Cancelled')
  AND completed_at < datetime('now', '-30 days')
`

// DeleteOldBatchJobs
//
//	DELETE FROM batch_jobs
//	WHERE status IN ('Completed', 'Failed', 'Cancelled')
//	  AND completed_at < datetime('now', '-30 days')
func (q *Queries) DeleteOldBatchJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldBatchJobs)
	return err
}

const getBatchJobByID = `-- name: GetBatchJobByID :one
SELECT id, batch_name, status, queued_at, started_at, completed_at, total_files, processed_files, successful_files, failed_files, continue_on_error, dry_run, max_concurrency, retry_count, max_retries, next_retry_at, metadata, error_message, created_date, last_update_date FROM batch_jobs
WHERE id = ?
LIMIT 1
`

// GetBatchJobByID
//
//	SELECT id, batch_name, status, queued_at, started_at, completed_at, total_files, processed_files, successful_files, failed_files, continue_on_error, dry_run, max_concurrency, retry_count, max_retries, next_retry_at, metadata, error_message, created_date, last_update_date FROM batch_jobs
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetBatchJobByID(ctx context.Context, id string) (BatchJob, error) {
	row := q.db.QueryRowContext(ctx, getBatchJobByID, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.BatchName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.SuccessfulFiles,
		&i.FailedFiles,
		&i.ContinueOnError,
		&i.DryRun,
		&i.MaxConcurrency,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.Metadata,
		&i.ErrorMessage,
		&i.CreatedDate,
		&i.LastUpdateDate,
	)
	return i, err
}

const getBatchJobItemByID = `-- name: GetBatchJobItemByID :one
SELECT id, batch_job_id, file_hash, confirmed_category, custom_target_path, status, target_path, actual_path, error_message, processing_time_ms, processed_at, metadata, created_date FROM batch_job_items
WHERE id = ?
LIMIT 1
`

// GetBatchJobItemByID
//
//	SELECT id, batch_job_id, file_hash, confirmed_category, custom_target_path, status, target_path, actual_path, error_message, processing_time_ms, processed_at, metadata, created_date FROM batch_job_items
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetBatchJobItemByID(ctx context.Context, id int64) (BatchJobItem, error) {
	row := q.db.QueryRowContext(ctx, getBatchJobItemByID, id)
	var i BatchJobItem
	err := row.Scan(
		&i.ID,
		&i.BatchJobID,
		&i.FileHash,
		&i.ConfirmedCategory,
		&i.CustomTargetPath,
		&i.Status,
		&i.TargetPath,
		&i.ActualPath,
		&i.ErrorMessage,
		&i.ProcessingTimeMs,
		&i.ProcessedAt,
		&i.Metadata,
		&i.CreatedDate,
	)
	return i, err
}

const getBatchJobItems = `-- name: GetBatchJobItems :many
SELECT id, batch_job_id, file_hash, confirmed_category, custom_target_path, status, target_path, actual_path, error_message, processing_time_ms, processed_at, metadata, created_date FROM batch_job_items
WHERE batch_job_id = ?
ORDER BY id ASC
`

// GetBatchJobItems
//
//	SELECT id, batch_job_id, file_hash, confirmed_category, custom_target_path, status, target_path, actual_path, error_message, processing_time_ms, processed_at, metadata, created_date FROM batch_job_items
//	WHERE batch_job_id = ?
//	ORDER BY id ASC
func (q *Queries) GetBatchJobItems(ctx context.Context, batchJobID string) ([]BatchJobItem, error) {
	rows, err := q.db.QueryContext(ctx, getBatchJobItems, batchJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchJobItem{}
	for rows.Next() {
		var i BatchJobItem
		if err := rows.Scan(
			&i.ID,
			&i.BatchJobID,
			&i.FileHash,
			&i.ConfirmedCategory,
			&i.CustomTargetPath,
			&i.Status,
			&i.TargetPath,
			&i.ActualPath,
			&i.ErrorMessage,
			&i.ProcessingTimeMs,
			&i.ProcessedAt,
			&i.Metadata,
			&i.CreatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchJobItemsByStatus = `-- name: GetBatchJobItemsByStatus :many
SELECT id, batch_job_id, file_hash, confirmed_category, custom_target_path, status, target_path, actual_path, error_message, processing_time_ms, processed_at, metadata, created_date FROM batch_job_items
WHERE batch_job_id = ?
  AND status = ?
ORDER BY id ASC
`

type GetBatchJobItemsByStatusParams struct {
	BatchJobID string `db:"batch_job_id" json:"batchJobId"`
	Status     string `db:"status" json:"status"`
}

// GetBatchJobItemsByStatus
//
//	SELECT id, batch_job_id, file_hash, confirmed_category, custom_target_path, status, target_path, actual_path, error_message, processing_time_ms, processed_at, metadata, created_date FROM batch_job_items
//	WHERE batch_job_id = ?
//	  AND status = ?
//	ORDER BY id ASC
func (q *Queries) GetBatchJobItemsByStatus(ctx context.Context, arg GetBatchJobItemsByStatusParams) ([]BatchJobItem, error) {
	rows, err := q.db.QueryContext(ctx, getBatchJobItemsByStatus, arg.BatchJobID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchJobItem{}
	for rows.Next() {
		var i BatchJobItem
		if err := rows.Scan(
			&i.ID,
			&i.BatchJobID,
			&i.FileHash,
			&i.ConfirmedCategory,
			&i.CustomTargetPath,
			&i.Status,
			&i.TargetPath,
			&i.ActualPath,
			&i.ErrorMessage,
			&i.ProcessingTimeMs,
			&i.ProcessedAt,
			&i.Metadata,
			&i.CreatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchJobItemsWithFileDetails = `-- name: GetBatchJobItemsWithFileDetails :many
SELECT
    bji.id, bji.batch_job_id, bji.file_hash, bji.confirmed_category, bji.custom_target_path, bji.status, bji.target_path, bji.actual_path, bji.error_message, bji.processing_time_ms, bji.processed_at, bji.metadata, bji.created_date,
    tf.FileName,
    tf.OriginalPath,
    tf.FileSize
FROM batch_job_items bji
INNER JOIN TrackedFiles tf ON bji.file_hash = tf.Hash
WHERE bji.batch_job_id = ?
  AND tf.IsActive = 1
ORDER BY bji.id ASC
`

type GetBatchJobItemsWithFileDetailsRow struct {
	ID                int64      `db:"id" json:"id"`
	BatchJobID        string     `db:"batch_job_id" json:"batchJobId"`
	FileHash          string     `db:"file_hash" json:"fileHash"`
	ConfirmedCategory string     `db:"confirmed_category" json:"confirmedCategory"`
	CustomTargetPath  *string    `db:"custom_target_path" json:"customTargetPath"`
	Status            string     `db:"status" json:"status"`
	TargetPath        *string    `db:"target_path" json:"targetPath"`
	ActualPath        *string    `db:"actual_path" json:"actualPath"`
	ErrorMessage      *string    `db:"error_message" json:"errorMessage"`
	ProcessingTimeMs  *int64     `db:"processing_time_ms" json:"processingTimeMs"`
	ProcessedAt       *time.Time `db:"processed_at" json:"processedAt"`
	Metadata          *string    `db:"metadata" json:"metadata"`
	CreatedDate       time.Time  `db:"created_date" json:"createdDate"`
	FileName          string     `db:"filename" json:"filename"`
	OriginalPath      string     `db:"originalpath" json:"originalpath"`
	FileSize          int64      `db:"filesize" json:"filesize"`
}

// GetBatchJobItemsWithFileDetails
//
//	SELECT
//	    bji.id, bji.batch_job_id, bji.file_hash, bji.confirmed_category, bji.custom_target_path, bji.status, bji.target_path, bji.actual_path, bji.error_message, bji.processing_time_ms, bji.processed_at, bji.metadata, bji.created_date,
//	    tf.FileName,
//	    tf.OriginalPath,
//	    tf.FileSize
//	FROM batch_job_items bji
//	INNER JOIN TrackedFiles tf ON bji.file_hash = tf.Hash
//	WHERE bji.batch_job_id = ?
//	  AND tf.IsActive = 1
//	ORDER BY bji.id ASC
func (q *Queries) GetBatchJobItemsWithFileDetails(ctx context.Context, batchJobID string) ([]GetBatchJobItemsWithFileDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBatchJobItemsWithFileDetails, batchJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBatchJobItemsWithFileDetailsRow{}
	for rows.Next() {
		var i GetBatchJobItemsWithFileDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchJobID,
			&i.FileHash,
			&i.ConfirmedCategory,
			&i.CustomTargetPath,
			&i.Status,
			&i.TargetPath,
			&i.ActualPath,
			&i.ErrorMessage,
			&i.ProcessingTimeMs,
			&i.ProcessedAt,
			&i.Metadata,
			&i.CreatedDate,
			&i.FileName,
			&i.OriginalPath,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchJobStatistics = `-- name: GetBatchJobStatistics :one
SELECT
    COUNT(*) as total_jobs,
    SUM(CASE WHEN status = 'Queued' THEN 1 ELSE 0 END) as queued_jobs,
    SUM(CASE WHEN status = 'Processing' THEN 1 ELSE 0 END) as processing_jobs,
    SUM(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END) as completed_jobs,
    SUM(CASE WHEN status = 'Failed' THEN 1 ELSE 0 END) as failed_jobs,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) as cancelled_jobs
FROM batch_jobs
`

type GetBatchJobStatisticsRow struct {
	TotalJobs      int64    `db:"total_jobs" json:"totalJobs"`
	QueuedJobs     *float64 `db:"queued_jobs" json:"queuedJobs"`
	ProcessingJobs *float64 `db:"processing_jobs" json:"processingJobs"`
	CompletedJobs  *float64 `db:"completed_jobs" json:"completedJobs"`
	FailedJobs     *float64 `db:"failed_jobs" json:"failedJobs"`
	CancelledJobs  *float64 `db:"cancelled_jobs" json:"cancelledJobs"`
}

// GetBatchJobStatistics
//
//	SELECT
//	    COUNT(*) as total_jobs,
//	    SUM(CASE WHEN status = 'Queued' THEN 1 ELSE 0 END) as queued_jobs,
//	    SUM(CASE WHEN status = 'Processing' THEN 1 ELSE 0 END) as processing_jobs,
//	    SUM(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END) as completed_jobs,
//	    SUM(CASE WHEN status = 'Failed' THEN 1 ELSE 0 END) as failed_jobs,
//	    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) as cancelled_jobs
//	FROM batch_jobs
func (q *Queries) GetBatchJobStatistics(ctx context.Context) (GetBatchJobStatisticsRow, error) {
	row := q.db.QueryRowContext(ctx, getBatchJobStatistics)
	var i GetBatchJobStatisticsRow
	err := row.Scan(
		&i.TotalJobs,
		&i.QueuedJobs,
		&i.ProcessingJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
		&i.CancelledJobs,
	)
	return i, err
}

const getQueuedBatchJobs = `-- name: GetQueuedBatchJobs :many
SELECT id, batch_name, status, queued_at, started_at, completed_at, total_files, processed_files, successful_files, failed_files, continue_on_error, dry_run, max_concurrency, retry_count, max_retries, next_retry_at, metadata, error_message, created_date, last_update_date FROM batch_jobs
WHERE status = 'Queued'
  AND (next_retry_at IS NULL OR next_retry_at <= datetime('now'))
ORDER BY queued_at ASC
LIMIT ?
`

// GetQueuedBatchJobs
//
//	SELECT id, batch_name, status, queued_at, started_at, completed_at, total_files, processed_files, successful_files, failed_files, continue_on_error, dry_run, max_concurrency, retry_count, max_retries, next_retry_at, metadata, error_message, created_date, last_update_date FROM batch_jobs
//	WHERE status = 'Queued'
//	  AND (next_retry_at IS NULL OR next_retry_at <= datetime('now'))
//	ORDER BY queued_at ASC
//	LIMIT ?
func (q *Queries) GetQueuedBatchJobs(ctx context.Context, limit int64) ([]BatchJob, error) {
	rows, err := q.db.QueryContext(ctx, getQueuedBatchJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchJob{}
	for rows.Next() {
		var i BatchJob
		if err := rows.Scan(
			&i.ID,
			&i.BatchName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TotalFiles,
			&i.ProcessedFiles,
			&i.SuccessfulFiles,
			&i.FailedFiles,
			&i.ContinueOnError,
			&i.DryRun,
			&i.MaxConcurrency,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.Metadata,
			&i.ErrorMessage,
			&i.CreatedDate,
			&i.LastUpdateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchJobs = `-- name: ListBatchJobs :many
SELECT id, batch_name, status, queued_at, started_at, completed_at, total_files, processed_files, successful_files, failed_files, continue_on_error, dry_run, max_concurrency, retry_count, max_retries, next_retry_at, metadata, error_message, created_date, last_update_date FROM batch_jobs
WHERE (?3 IS NULL OR status = ?3)
ORDER BY queued_at DESC
LIMIT ? OFFSET ?
`

type ListBatchJobsParams struct {
	Status interface{} `db:"status" json:"status"`
	Limit  int64       `db:"limit" json:"limit"`
	Offset int64       `db:"offset" json:"offset"`
}

// ListBatchJobs
//
//	SELECT id, batch_name, status, queued_at, started_at, completed_at, total_files, processed_files, successful_files, failed_files, continue_on_error, dry_run, max_concurrency, retry_count, max_retries, next_retry_at, metadata, error_message, created_date, last_update_date FROM batch_jobs
//	WHERE (?3 IS NULL OR status = ?3)
//	ORDER BY queued_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) ListBatchJobs(ctx context.Context, arg ListBatchJobsParams) ([]BatchJob, error) {
	rows, err := q.db.QueryContext(ctx, listBatchJobs, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchJob{}
	for rows.Next() {
		var i BatchJob
		if err := rows.Scan(
			&i.ID,
			&i.BatchName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TotalFiles,
			&i.ProcessedFiles,
			&i.SuccessfulFiles,
			&i.FailedFiles,
			&i.ContinueOnError,
			&i.DryRun,
			&i.MaxConcurrency,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.Metadata,
			&i.ErrorMessage,
			&i.CreatedDate,
			&i.LastUpdateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchJobCancelled = `-- name: UpdateBatchJobCancelled :exec
UPDATE batch_jobs
SET status = 'Cancelled',
    completed_at = ?,
    last_update_date = ?
WHERE id = ?
`

type UpdateBatchJobCancelledParams struct {
	CompletedAt    *time.Time `db:"completed_at" json:"completedAt"`
	LastUpdateDate time.Time  `db:"last_update_date" json:"lastUpdateDate"`
	ID             string     `db:"id" json:"id"`
}

// UpdateBatchJobCancelled
//
//	UPDATE batch_jobs
//	SET status = 'Cancelled',
//	    completed_at = ?,
//	    last_update_date = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobCancelled(ctx context.Context, arg UpdateBatchJobCancelledParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobCancelled, arg.CompletedAt, arg.LastUpdateDate, arg.ID)
	return err
}

const updateBatchJobCompleted = `-- name: UpdateBatchJobCompleted :exec
UPDATE batch_jobs
SET status = ?,
    completed_at = ?,
    processed_files = ?,
    successful_files = ?,
    failed_files = ?,
    last_update_date = ?
WHERE id = ?
`

type UpdateBatchJobCompletedParams struct {
	Status          string     `db:"status" json:"status"`
	CompletedAt     *time.Time `db:"completed_at" json:"completedAt"`
	ProcessedFiles  *int64     `db:"processed_files" json:"processedFiles"`
	SuccessfulFiles *int64     `db:"successful_files" json:"successfulFiles"`
	FailedFiles     *int64     `db:"failed_files" json:"failedFiles"`
	LastUpdateDate  time.Time  `db:"last_update_date" json:"lastUpdateDate"`
	ID              string     `db:"id" json:"id"`
}

// UpdateBatchJobCompleted
//
//	UPDATE batch_jobs
//	SET status = ?,
//	    completed_at = ?,
//	    processed_files = ?,
//	    successful_files = ?,
//	    failed_files = ?,
//	    last_update_date = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobCompleted(ctx context.Context, arg UpdateBatchJobCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobCompleted,
		arg.Status,
		arg.CompletedAt,
		arg.ProcessedFiles,
		arg.SuccessfulFiles,
		arg.FailedFiles,
		arg.LastUpdateDate,
		arg.ID,
	)
	return err
}

const updateBatchJobFailed = `-- name: UpdateBatchJobFailed :exec
UPDATE batch_jobs
SET status = 'Failed',
    completed_at = ?,
    error_message = ?,
    retry_count = ?,
    next_retry_at = ?,
    last_update_date = ?
WHERE id = ?
`

type UpdateBatchJobFailedParams struct {
	CompletedAt    *time.Time `db:"completed_at" json:"completedAt"`
	ErrorMessage   *string    `db:"error_message" json:"errorMessage"`
	RetryCount     *int64     `db:"retry_count" json:"retryCount"`
	NextRetryAt    *time.Time `db:"next_retry_at" json:"nextRetryAt"`
	LastUpdateDate time.Time  `db:"last_update_date" json:"lastUpdateDate"`
	ID             string     `db:"id" json:"id"`
}

// UpdateBatchJobFailed
//
//	UPDATE batch_jobs
//	SET status = 'Failed',
//	    completed_at = ?,
//	    error_message = ?,
//	    retry_count = ?,
//	    next_retry_at = ?,
//	    last_update_date = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobFailed(ctx context.Context, arg UpdateBatchJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobFailed,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.LastUpdateDate,
		arg.ID,
	)
	return err
}

const updateBatchJobItemCompleted = `-- name: UpdateBatchJobItemCompleted :exec
UPDATE batch_job_items
SET status = 'Completed',
    target_path = ?,
    actual_path = ?,
    processing_time_ms = ?,
    processed_at = ?
WHERE id = ?
`

type UpdateBatchJobItemCompletedParams struct {
	TargetPath       *string    `db:"target_path" json:"targetPath"`
	ActualPath       *string    `db:"actual_path" json:"actualPath"`
	ProcessingTimeMs *int64     `db:"processing_time_ms" json:"processingTimeMs"`
	ProcessedAt      *time.Time `db:"processed_at" json:"processedAt"`
	ID               int64      `db:"id" json:"id"`
}

// UpdateBatchJobItemCompleted
//
//	UPDATE batch_job_items
//	SET status = 'Completed',
//	    target_path = ?,
//	    actual_path = ?,
//	    processing_time_ms = ?,
//	    processed_at = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobItemCompleted(ctx context.Context, arg UpdateBatchJobItemCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobItemCompleted,
		arg.TargetPath,
		arg.ActualPath,
		arg.ProcessingTimeMs,
		arg.ProcessedAt,
		arg.ID,
	)
	return err
}

const updateBatchJobItemFailed = `-- name: UpdateBatchJobItemFailed :exec
UPDATE batch_job_items
SET status = 'Failed',
    error_message = ?,
    processing_time_ms = ?,
    processed_at = ?
WHERE id = ?
`

type UpdateBatchJobItemFailedParams struct {
	ErrorMessage     *string    `db:"error_message" json:"errorMessage"`
	ProcessingTimeMs *int64     `db:"processing_time_ms" json:"processingTimeMs"`
	ProcessedAt      *time.Time `db:"processed_at" json:"processedAt"`
	ID               int64      `db:"id" json:"id"`
}

// UpdateBatchJobItemFailed
//
//	UPDATE batch_job_items
//	SET status = 'Failed',
//	    error_message = ?,
//	    processing_time_ms = ?,
//	    processed_at = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobItemFailed(ctx context.Context, arg UpdateBatchJobItemFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobItemFailed,
		arg.ErrorMessage,
		arg.ProcessingTimeMs,
		arg.ProcessedAt,
		arg.ID,
	)
	return err
}

const updateBatchJobItemProcessing = `-- name: UpdateBatchJobItemProcessing :exec
UPDATE batch_job_items
SET status = 'Processing'
WHERE id = ?
`

// UpdateBatchJobItemProcessing
//
//	UPDATE batch_job_items
//	SET status = 'Processing'
//	WHERE id = ?
func (q *Queries) UpdateBatchJobItemProcessing(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobItemProcessing, id)
	return err
}

const updateBatchJobItemStatus = `-- name: UpdateBatchJobItemStatus :exec
UPDATE batch_job_items
SET status = ?
WHERE id = ?
`

type UpdateBatchJobItemStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int64  `db:"id" json:"id"`
}

// UpdateBatchJobItemStatus
//
//	UPDATE batch_job_items
//	SET status = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobItemStatus(ctx context.Context, arg UpdateBatchJobItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobItemStatus, arg.Status, arg.ID)
	return err
}

const updateBatchJobProgress = `-- name: UpdateBatchJobProgress :exec
UPDATE batch_jobs
SET processed_files = ?,
    successful_files = ?,
    failed_files = ?,
    last_update_date = ?
WHERE id = ?
`

type UpdateBatchJobProgressParams struct {
	ProcessedFiles  *int64    `db:"processed_files" json:"processedFiles"`
	SuccessfulFiles *int64    `db:"successful_files" json:"successfulFiles"`
	FailedFiles     *int64    `db:"failed_files" json:"failedFiles"`
	LastUpdateDate  time.Time `db:"last_update_date" json:"lastUpdateDate"`
	ID              string    `db:"id" json:"id"`
}

// UpdateBatchJobProgress
//
//	UPDATE batch_jobs
//	SET processed_files = ?,
//	    successful_files = ?,
//	    failed_files = ?,
//	    last_update_date = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobProgress(ctx context.Context, arg UpdateBatchJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobProgress,
		arg.ProcessedFiles,
		arg.SuccessfulFiles,
		arg.FailedFiles,
		arg.LastUpdateDate,
		arg.ID,
	)
	return err
}

const updateBatchJobStarted = `-- name: UpdateBatchJobStarted :exec
UPDATE batch_jobs
SET status = 'Processing',
    started_at = ?,
    last_update_date = ?
WHERE id = ?
`

type UpdateBatchJobStartedParams struct {
	StartedAt      *time.Time `db:"started_at" json:"startedAt"`
	LastUpdateDate time.Time  `db:"last_update_date" json:"lastUpdateDate"`
	ID             string     `db:"id" json:"id"`
}

// UpdateBatchJobStarted
//
//	UPDATE batch_jobs
//	SET status = 'Processing',
//	    started_at = ?,
//	    last_update_date = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobStarted(ctx context.Context, arg UpdateBatchJobStartedParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobStarted, arg.StartedAt, arg.LastUpdateDate, arg.ID)
	return err
}

const updateBatchJobStatus = `-- name: UpdateBatchJobStatus :exec
UPDATE batch_jobs
SET status = ?,
    last_update_date = ?
WHERE id = ?
`

type UpdateBatchJobStatusParams struct {
	Status         string    `db:"status" json:"status"`
	LastUpdateDate time.Time `db:"last_update_date" json:"lastUpdateDate"`
	ID             string    `db:"id" json:"id"`
}

// UpdateBatchJobStatus
//
//	UPDATE batch_jobs
//	SET status = ?,
//	    last_update_date = ?
//	WHERE id = ?
func (q *Queries) UpdateBatchJobStatus(ctx context.Context, arg UpdateBatchJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchJobStatus, arg.Status, arg.LastUpdateDate, arg.ID)
	return err
}
