// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
	"strings"
	"time"
)

const countAllFiles = `-- name: CountAllFiles :one
SELECT COUNT(*) FROM TrackedFiles
WHERE IsActive = 1
`

func (q *Queries) CountAllFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByStatus = `-- name: CountFilesByStatus :one
SELECT COUNT(*) FROM TrackedFiles
WHERE Status = ? AND IsActive = 1
`

func (q *Queries) CountFilesByStatus(ctx context.Context, status int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByStatuses = `-- name: CountFilesByStatuses :one
SELECT COUNT(*) FROM TrackedFiles
WHERE Status IN (/*SLICE:statuses*/?)
  AND IsActive = 1
  AND (?2 IS NULL OR Category = ?2)
  AND (?3 IS NULL
       OR FileName LIKE '%' || ?3 || '%'
       OR Category LIKE '%' || ?3 || '%')
`

type CountFilesByStatusesParams struct {
	Statuses   []int64     `db:"statuses" json:"statuses"`
	Category   interface{} `db:"category" json:"category"`
	SearchTerm interface{} `db:"search_term" json:"searchTerm"`
}

func (q *Queries) CountFilesByStatuses(ctx context.Context, arg CountFilesByStatusesParams) (int64, error) {
	query := countFilesByStatuses
	var queryParams []interface{}
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Category)
	queryParams = append(queryParams, arg.SearchTerm)
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :exec
INSERT INTO TrackedFiles (
    Hash, FileName, OriginalPath, FileSize, Status,
    CreatedDate, LastUpdateDate, IsActive
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	Hash           string    `db:"hash" json:"hash"`
	Filename       string    `db:"filename" json:"filename"`
	Originalpath   string    `db:"originalpath" json:"originalpath"`
	Filesize       int64     `db:"filesize" json:"filesize"`
	Status         int64     `db:"status" json:"status"`
	Createddate    time.Time `db:"createddate" json:"createddate"`
	Lastupdatedate time.Time `db:"lastupdatedate" json:"lastupdatedate"`
	Isactive       int64     `db:"isactive" json:"isactive"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.Hash,
		arg.Filename,
		arg.Originalpath,
		arg.Filesize,
		arg.Status,
		arg.Createddate,
		arg.Lastupdatedate,
		arg.Isactive,
	)
	return err
}

const existsByHash = `-- name: ExistsByHash :one
SELECT COUNT(*) > 0
FROM TrackedFiles
WHERE Hash = ?
  AND IsActive = 1
`

func (q *Queries) ExistsByHash(ctx context.Context, hash string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByHash, hash)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsByOriginalPath = `-- name: ExistsByOriginalPath :one
SELECT COUNT(*) > 0
FROM TrackedFiles
WHERE OriginalPath = ?
  AND IsActive = 1
`

func (q *Queries) ExistsByOriginalPath(ctx context.Context, originalpath string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByOriginalPath, originalpath)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllFiles = `-- name: GetAllFiles :many

SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE IsActive = 1
ORDER BY CreatedDate DESC
LIMIT ? OFFSET ?
`

type GetAllFilesParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

// Batch Operations
func (q *Queries) GetAllFiles(ctx context.Context, arg GetAllFilesParams) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getAllFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctCategories = `-- name: GetDistinctCategories :many
SELECT DISTINCT Category
FROM TrackedFiles
WHERE Category IS NOT NULL
  AND IsActive = 1
ORDER BY Category ASC
`

func (q *Queries) GetDistinctCategories(ctx context.Context) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByHash = `-- name: GetFileByHash :one

SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Hash = ? AND IsActive = 1
LIMIT 1
`

// TrackedFile CRUD Operations
func (q *Queries) GetFileByHash(ctx context.Context, hash string) (Trackedfile, error) {
	row := q.db.QueryRowContext(ctx, getFileByHash, hash)
	var i Trackedfile
	err := row.Scan(
		&i.Hash,
		&i.Filename,
		&i.Originalpath,
		&i.Filesize,
		&i.Status,
		&i.Suggestedcategory,
		&i.Confidence,
		&i.Category,
		&i.Targetpath,
		&i.Movedtopath,
		&i.Classifiedat,
		&i.Movedat,
		&i.Lasterror,
		&i.Lasterrorat,
		&i.Retrycount,
		&i.Createddate,
		&i.Lastupdatedate,
		&i.Note,
		&i.Isactive,
	)
	return i, err
}

const getFileByHashIncludeDeleted = `-- name: GetFileByHashIncludeDeleted :one
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Hash = ?
LIMIT 1
`

func (q *Queries) GetFileByHashIncludeDeleted(ctx context.Context, hash string) (Trackedfile, error) {
	row := q.db.QueryRowContext(ctx, getFileByHashIncludeDeleted, hash)
	var i Trackedfile
	err := row.Scan(
		&i.Hash,
		&i.Filename,
		&i.Originalpath,
		&i.Filesize,
		&i.Status,
		&i.Suggestedcategory,
		&i.Confidence,
		&i.Category,
		&i.Targetpath,
		&i.Movedtopath,
		&i.Classifiedat,
		&i.Movedat,
		&i.Lasterror,
		&i.Lasterrorat,
		&i.Retrycount,
		&i.Createddate,
		&i.Lastupdatedate,
		&i.Note,
		&i.Isactive,
	)
	return i, err
}

const getFilesAwaitingConfirmation = `-- name: GetFilesAwaitingConfirmation :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 2  -- FileStatus.Classified
  AND IsActive = 1
ORDER BY ClassifiedAt DESC
`

func (q *Queries) GetFilesAwaitingConfirmation(ctx context.Context) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesAwaitingConfirmation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByCategory = `-- name: GetFilesByCategory :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Category = ?
  AND IsActive = 1
ORDER BY MovedAt DESC
`

func (q *Queries) GetFilesByCategory(ctx context.Context, category *string) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByStatus = `-- name: GetFilesByStatus :many

SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = ? AND IsActive = 1
ORDER BY CreatedDate DESC
LIMIT ? OFFSET ?
`

type GetFilesByStatusParams struct {
	Status int64 `db:"status" json:"status"`
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

// Workflow Queries
func (q *Queries) GetFilesByStatus(ctx context.Context, arg GetFilesByStatusParams) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByStatuses = `-- name: GetFilesByStatuses :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status IN (/*SLICE:statuses*/?)
  AND IsActive = 1
  AND (?4 IS NULL OR Category = ?4)
  AND (?5 IS NULL
       OR FileName LIKE '%' || ?5 || '%'
       OR Category LIKE '%' || ?5 || '%')
ORDER BY
  CASE WHEN sqlc.narg('order_by') = 'CreatedDate' THEN CreatedDate END ASC,
  CASE WHEN sqlc.narg('order_by') = 'LastUpdateDate' THEN LastUpdateDate END DESC,
  CASE WHEN sqlc.narg('order_by') = 'FileName' THEN FileName END ASC,
  LastUpdateDate DESC
LIMIT ? OFFSET ?
`

type GetFilesByStatusesParams struct {
	Statuses   []int64     `db:"statuses" json:"statuses"`
	Category   interface{} `db:"category" json:"category"`
	SearchTerm interface{} `db:"search_term" json:"searchTerm"`
	Limit      int64       `db:"limit" json:"limit"`
	Offset     int64       `db:"offset" json:"offset"`
}

func (q *Queries) GetFilesByStatuses(ctx context.Context, arg GetFilesByStatusesParams) ([]Trackedfile, error) {
	query := getFilesByStatuses
	var queryParams []interface{}
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Category)
	queryParams = append(queryParams, arg.SearchTerm)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesExceedingRetryLimit = `-- name: GetFilesExceedingRetryLimit :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 6  -- FileStatus.Error
  AND RetryCount >= ?
  AND IsActive = 1
ORDER BY RetryCount DESC, LastErrorAt DESC
`

func (q *Queries) GetFilesExceedingRetryLimit(ctx context.Context, retrycount int64) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesExceedingRetryLimit, retrycount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesProcessedInRange = `-- name: GetFilesProcessedInRange :many

SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE CreatedDate BETWEEN ? AND ?
  AND IsActive = 1
ORDER BY CreatedDate DESC
`

type GetFilesProcessedInRangeParams struct {
	Createddate   time.Time `db:"createddate" json:"createddate"`
	Createddate_2 time.Time `db:"createddate_2" json:"createddate2"`
}

// Temporal Queries
func (q *Queries) GetFilesProcessedInRange(ctx context.Context, arg GetFilesProcessedInRangeParams) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesProcessedInRange, arg.Createddate, arg.Createddate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesReadyForClassification = `-- name: GetFilesReadyForClassification :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 0  -- FileStatus.New
  AND IsActive = 1
ORDER BY CreatedDate ASC
LIMIT ?
`

func (q *Queries) GetFilesReadyForClassification(ctx context.Context, limit int64) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesReadyForClassification, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesReadyForMoving = `-- name: GetFilesReadyForMoving :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 3  -- FileStatus.ReadyToMove
  AND IsActive = 1
ORDER BY LastUpdateDate ASC
LIMIT ?
`

func (q *Queries) GetFilesReadyForMoving(ctx context.Context, limit int64) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesReadyForMoving, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesReadyForRetry = `-- name: GetFilesReadyForRetry :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 7  -- FileStatus.Retry
  AND IsActive = 1
ORDER BY LastErrorAt ASC
LIMIT ?
`

func (q *Queries) GetFilesReadyForRetry(ctx context.Context, limit int64) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesReadyForRetry, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesWithErrors = `-- name: GetFilesWithErrors :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 6  -- FileStatus.Error
  AND IsActive = 1
ORDER BY LastErrorAt DESC
`

func (q *Queries) GetFilesWithErrors(ctx context.Context) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getFilesWithErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighConfidenceFiles = `-- name: GetHighConfidenceFiles :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Confidence >= ?
  AND IsActive = 1
ORDER BY Confidence DESC
`

func (q *Queries) GetHighConfidenceFiles(ctx context.Context, confidence float64) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getHighConfidenceFiles, confidence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLowConfidenceFiles = `-- name: GetLowConfidenceFiles :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Confidence < ?
  AND Confidence > 0
  AND IsActive = 1
ORDER BY Confidence ASC
`

func (q *Queries) GetLowConfidenceFiles(ctx context.Context, confidence float64) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getLowConfidenceFiles, confidence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingStats = `-- name: GetProcessingStats :many

SELECT Status, COUNT(*) as Count
FROM TrackedFiles
WHERE IsActive = 1
GROUP BY Status
`

type GetProcessingStatsRow struct {
	Status int64 `db:"status" json:"status"`
	Count  int64 `db:"count" json:"count"`
}

// Analytics Queries
func (q *Queries) GetProcessingStats(ctx context.Context) ([]GetProcessingStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProcessingStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProcessingStatsRow{}
	for rows.Next() {
		var i GetProcessingStatsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyMovedFiles = `-- name: GetRecentlyMovedFiles :many
SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE Status = 5  -- FileStatus.Moved
  AND MovedAt >= datetime('now', ?)  -- e.g., '-24 hours'
  AND IsActive = 1
ORDER BY MovedAt DESC
`

func (q *Queries) GetRecentlyMovedFiles(ctx context.Context, datetime interface{}) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, getRecentlyMovedFiles, datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE TrackedFiles
SET IsActive = 1,
    LastUpdateDate = ?,
    Note = ?
WHERE Hash = ?
`

type RestoreFileParams struct {
	Lastupdatedate time.Time `db:"lastupdatedate" json:"lastupdatedate"`
	Note           *string   `db:"note" json:"note"`
	Hash           string    `db:"hash" json:"hash"`
}

func (q *Queries) RestoreFile(ctx context.Context, arg RestoreFileParams) error {
	_, err := q.db.ExecContext(ctx, restoreFile, arg.Lastupdatedate, arg.Note, arg.Hash)
	return err
}

const searchByFilename = `-- name: SearchByFilename :many

SELECT hash, filename, originalpath, filesize, status, suggestedcategory, confidence, category, targetpath, movedtopath, classifiedat, movedat, lasterror, lasterrorat, retrycount, createddate, lastupdatedate, note, isactive FROM TrackedFiles
WHERE FileName LIKE '%' || ? || '%'
  AND IsActive = 1
ORDER BY FileName ASC
LIMIT ? OFFSET ?
`

type SearchByFilenameParams struct {
	Column1 *string `db:"column_1" json:"column1"`
	Limit   int64   `db:"limit" json:"limit"`
	Offset  int64   `db:"offset" json:"offset"`
}

// Lookup Queries
func (q *Queries) SearchByFilename(ctx context.Context, arg SearchByFilenameParams) ([]Trackedfile, error) {
	rows, err := q.db.QueryContext(ctx, searchByFilename, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trackedfile{}
	for rows.Next() {
		var i Trackedfile
		if err := rows.Scan(
			&i.Hash,
			&i.Filename,
			&i.Originalpath,
			&i.Filesize,
			&i.Status,
			&i.Suggestedcategory,
			&i.Confidence,
			&i.Category,
			&i.Targetpath,
			&i.Movedtopath,
			&i.Classifiedat,
			&i.Movedat,
			&i.Lasterror,
			&i.Lasterrorat,
			&i.Retrycount,
			&i.Createddate,
			&i.Lastupdatedate,
			&i.Note,
			&i.Isactive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE TrackedFiles
SET IsActive = 0,
    LastUpdateDate = ?,
    Note = ?
WHERE Hash = ?
`

type SoftDeleteFileParams struct {
	Lastupdatedate time.Time `db:"lastupdatedate" json:"lastupdatedate"`
	Note           *string   `db:"note" json:"note"`
	Hash           string    `db:"hash" json:"hash"`
}

func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFile, arg.Lastupdatedate, arg.Note, arg.Hash)
	return err
}

const updateCategoryConfirmation = `-- name: UpdateCategoryConfirmation :exec
UPDATE TrackedFiles
SET Category = ?,
    TargetPath = ?,
    Status = ?,
    LastUpdateDate = ?
WHERE Hash = ? AND IsActive = 1
`

type UpdateCategoryConfirmationParams struct {
	Category       *string   `db:"category" json:"category"`
	Targetpath     *string   `db:"targetpath" json:"targetpath"`
	Status         int64     `db:"status" json:"status"`
	Lastupdatedate time.Time `db:"lastupdatedate" json:"lastupdatedate"`
	Hash           string    `db:"hash" json:"hash"`
}

func (q *Queries) UpdateCategoryConfirmation(ctx context.Context, arg UpdateCategoryConfirmationParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryConfirmation,
		arg.Category,
		arg.Targetpath,
		arg.Status,
		arg.Lastupdatedate,
		arg.Hash,
	)
	return err
}

const updateClassification = `-- name: UpdateClassification :exec
UPDATE TrackedFiles
SET SuggestedCategory = ?,
    Confidence = ?,
    ClassifiedAt = ?,
    Status = ?,
    LastUpdateDate = ?
WHERE Hash = ? AND IsActive = 1
`

type UpdateClassificationParams struct {
	Suggestedcategory *string    `db:"suggestedcategory" json:"suggestedcategory"`
	Confidence        float64    `db:"confidence" json:"confidence"`
	Classifiedat      *time.Time `db:"classifiedat" json:"classifiedat"`
	Status            int64      `db:"status" json:"status"`
	Lastupdatedate    time.Time  `db:"lastupdatedate" json:"lastupdatedate"`
	Hash              string     `db:"hash" json:"hash"`
}

func (q *Queries) UpdateClassification(ctx context.Context, arg UpdateClassificationParams) error {
	_, err := q.db.ExecContext(ctx, updateClassification,
		arg.Suggestedcategory,
		arg.Confidence,
		arg.Classifiedat,
		arg.Status,
		arg.Lastupdatedate,
		arg.Hash,
	)
	return err
}

const updateFile = `-- name: UpdateFile :exec
UPDATE TrackedFiles
SET FileName = ?,
    OriginalPath = ?,
    FileSize = ?,
    Status = ?,
    SuggestedCategory = ?,
    Confidence = ?,
    Category = ?,
    TargetPath = ?,
    ClassifiedAt = ?,
    MovedAt = ?,
    LastError = ?,
    LastErrorAt = ?,
    RetryCount = ?,
    LastUpdateDate = ?,
    Note = ?
WHERE Hash = ? AND IsActive = 1
`

type UpdateFileParams struct {
	Filename          string     `db:"filename" json:"filename"`
	Originalpath      string     `db:"originalpath" json:"originalpath"`
	Filesize          int64      `db:"filesize" json:"filesize"`
	Status            int64      `db:"status" json:"status"`
	Suggestedcategory *string    `db:"suggestedcategory" json:"suggestedcategory"`
	Confidence        float64    `db:"confidence" json:"confidence"`
	Category          *string    `db:"category" json:"category"`
	Targetpath        *string    `db:"targetpath" json:"targetpath"`
	Classifiedat      *time.Time `db:"classifiedat" json:"classifiedat"`
	Movedat           *time.Time `db:"movedat" json:"movedat"`
	Lasterror         *string    `db:"lasterror" json:"lasterror"`
	Lasterrorat       *time.Time `db:"lasterrorat" json:"lasterrorat"`
	Retrycount        int64      `db:"retrycount" json:"retrycount"`
	Lastupdatedate    time.Time  `db:"lastupdatedate" json:"lastupdatedate"`
	Note              *string    `db:"note" json:"note"`
	Hash              string     `db:"hash" json:"hash"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.ExecContext(ctx, updateFile,
		arg.Filename,
		arg.Originalpath,
		arg.Filesize,
		arg.Status,
		arg.Suggestedcategory,
		arg.Confidence,
		arg.Category,
		arg.Targetpath,
		arg.Classifiedat,
		arg.Movedat,
		arg.Lasterror,
		arg.Lasterrorat,
		arg.Retrycount,
		arg.Lastupdatedate,
		arg.Note,
		arg.Hash,
	)
	return err
}

const updateMoveCompletion = `-- name: UpdateMoveCompletion :exec
UPDATE TrackedFiles
SET MovedToPath = ?,
    MovedAt = ?,
    Status = ?,
    LastUpdateDate = ?
WHERE Hash = ? AND IsActive = 1
`

type UpdateMoveCompletionParams struct {
	Movedtopath    *string    `db:"movedtopath" json:"movedtopath"`
	Movedat        *time.Time `db:"movedat" json:"movedat"`
	Status         int64      `db:"status" json:"status"`
	Lastupdatedate time.Time  `db:"lastupdatedate" json:"lastupdatedate"`
	Hash           string     `db:"hash" json:"hash"`
}

func (q *Queries) UpdateMoveCompletion(ctx context.Context, arg UpdateMoveCompletionParams) error {
	_, err := q.db.ExecContext(ctx, updateMoveCompletion,
		arg.Movedtopath,
		arg.Movedat,
		arg.Status,
		arg.Lastupdatedate,
		arg.Hash,
	)
	return err
}
