// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Trackedfile struct {
	Hash              string     `db:"hash" json:"hash"`
	Filename          string     `db:"filename" json:"filename"`
	Originalpath      string     `db:"originalpath" json:"originalpath"`
	Filesize          int64      `db:"filesize" json:"filesize"`
	Status            int64      `db:"status" json:"status"`
	Suggestedcategory *string    `db:"suggestedcategory" json:"suggestedcategory"`
	Confidence        float64    `db:"confidence" json:"confidence"`
	Category          *string    `db:"category" json:"category"`
	Targetpath        *string    `db:"targetpath" json:"targetpath"`
	Movedtopath       *string    `db:"movedtopath" json:"movedtopath"`
	Classifiedat      *time.Time `db:"classifiedat" json:"classifiedat"`
	Movedat           *time.Time `db:"movedat" json:"movedat"`
	Lasterror         *string    `db:"lasterror" json:"lasterror"`
	Lasterrorat       *time.Time `db:"lasterrorat" json:"lasterrorat"`
	Retrycount        int64      `db:"retrycount" json:"retrycount"`
	Createddate       time.Time  `db:"createddate" json:"createddate"`
	Lastupdatedate    time.Time  `db:"lastupdatedate" json:"lastupdatedate"`
	Note              *string    `db:"note" json:"note"`
	Isactive          int64      `db:"isactive" json:"isactive"`
}
