// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Trackedfile struct {
	Hash              string     `db:"Hash" json:"hash"`
	Filename          string     `db:"FileName" json:"fileName"`
	Originalpath      string     `db:"OriginalPath" json:"originalPath"`
	Filesize          int64      `db:"FileSize" json:"fileSize"`
	Status            int64      `db:"Status" json:"status"`
	Suggestedcategory *string    `db:"SuggestedCategory" json:"suggestedCategory"`
	Confidence        float64    `db:"Confidence" json:"confidence"`
	Category          *string    `db:"Category" json:"category"`
	Targetpath        *string    `db:"TargetPath" json:"targetPath"`
	Movedtopath       *string    `db:"MovedToPath" json:"movedToPath"`
	Classifiedat      *time.Time `db:"ClassifiedAt" json:"classifiedAt"`
	Movedat           *time.Time `db:"MovedAt" json:"movedAt"`
	Lasterror         *string    `db:"LastError" json:"lastError"`
	Lasterrorat       *time.Time `db:"LastErrorAt" json:"lastErrorAt"`
	Retrycount        int64      `db:"RetryCount" json:"retryCount"`
	Createddate       time.Time  `db:"CreatedDate" json:"createdDate"`
	Lastupdatedate    time.Time  `db:"LastUpdateDate" json:"lastUpdateDate"`
	Note              *string    `db:"Note" json:"note"`
	Isactive          bool       `db:"IsActive" json:"isActive"`
}
