// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountAllFiles(ctx context.Context) (int64, error)
	CountFilesByStatus(ctx context.Context, status int64) (int64, error)
	CountFilesByStatuses(ctx context.Context, arg CountFilesByStatusesParams) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) error
	ExistsByHash(ctx context.Context, hash string) (bool, error)
	ExistsByOriginalPath(ctx context.Context, originalpath string) (bool, error)
	// Batch Operations
	GetAllFiles(ctx context.Context, arg GetAllFilesParams) ([]Trackedfile, error)
	GetDistinctCategories(ctx context.Context) ([]*string, error)
	// TrackedFile CRUD Operations
	GetFileByHash(ctx context.Context, hash string) (Trackedfile, error)
	GetFileByHashIncludeDeleted(ctx context.Context, hash string) (Trackedfile, error)
	GetFilesAwaitingConfirmation(ctx context.Context) ([]Trackedfile, error)
	GetFilesByCategory(ctx context.Context, category *string) ([]Trackedfile, error)
	// Workflow Queries
	GetFilesByStatus(ctx context.Context, arg GetFilesByStatusParams) ([]Trackedfile, error)
	GetFilesByStatuses(ctx context.Context, arg GetFilesByStatusesParams) ([]Trackedfile, error)
	GetFilesExceedingRetryLimit(ctx context.Context, retrycount int64) ([]Trackedfile, error)
	// Temporal Queries
	GetFilesProcessedInRange(ctx context.Context, arg GetFilesProcessedInRangeParams) ([]Trackedfile, error)
	GetFilesReadyForClassification(ctx context.Context, limit int64) ([]Trackedfile, error)
	GetFilesReadyForMoving(ctx context.Context, limit int64) ([]Trackedfile, error)
	GetFilesReadyForRetry(ctx context.Context, limit int64) ([]Trackedfile, error)
	GetFilesWithErrors(ctx context.Context) ([]Trackedfile, error)
	GetHighConfidenceFiles(ctx context.Context, confidence float64) ([]Trackedfile, error)
	GetLowConfidenceFiles(ctx context.Context, confidence float64) ([]Trackedfile, error)
	// Analytics Queries
	GetProcessingStats(ctx context.Context) ([]GetProcessingStatsRow, error)
	GetRecentlyMovedFiles(ctx context.Context, datetime interface{}) ([]Trackedfile, error)
	RestoreFile(ctx context.Context, arg RestoreFileParams) error
	// Lookup Queries
	SearchByFilename(ctx context.Context, arg SearchByFilenameParams) ([]Trackedfile, error)
	SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) error
	UpdateCategoryConfirmation(ctx context.Context, arg UpdateCategoryConfirmationParams) error
	UpdateClassification(ctx context.Context, arg UpdateClassificationParams) error
	UpdateFile(ctx context.Context, arg UpdateFileParams) error
	UpdateMoveCompletion(ctx context.Context, arg UpdateMoveCompletionParams) error
}

var _ Querier = (*Queries)(nil)
